name: mmdetection_dvc
channels:
  - pytorch
  - anaconda
  - nvidia
dependencies:
  - python=3.9
  - pytorch=1.9
  - torchvision=0.10.0
  - cudatoolkit=11.1 
  - pip=21.1.3
  - opencv=4.0.1
  - dvc=2.5.4
  - pip:
    - pyodi
    - mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
    - mmdet==2.14.0

