stages:

  prepare_data:
    foreach:
      - train
      - val
    do:
      cmd: python src/prepare_data.py
        --coco_file data/coco_sample/annotations/split_${item}.json
        --output_file processed_data/${item}_split_with_ann_id.json
      deps:
        - data/coco_sample/annotations/split_${item}.json
        - src/prepare_data.py
      outs:
        - processed_data/${item}_split_with_ann_id.json

  train:
    cmd: python src/train.py
      --dataset configs/coco_sample.py
      --model configs/retinanet_r50_fpn.py
      --schedule configs/schedule_1x.py
      --runtime configs/runtime.py
      --work_dir training/checkpoints
    deps:
      - configs/
      - processed_data
      - src/train.py
    outs:
      - training/checkpoints
    live:
      training/metrics:
        summary: true
        html: true
    params:
      - optimizer.weight_decay
